language: php

env:
  global:
  - COMPOSER_ROOT_VERSION="3.1.x-dev"

matrix:
  include:
  - php: 7.1
    env: DB=MYSQL INSTALLER_VERSION=4.2.2 PHPUNIT_TEST=1
  - php: 7.2
    env: DB=MYSQL INSTALLER_VERSION=4.2.2 PHPUNIT_TEST=1

before_script:
- phpenv rehash
- phpenv config-rm xdebug.ini

- composer validate
- composer require silverstripe/installer:$INSTALLER_VERSION  --no-update
- if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.x-dev; fi
- composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
- if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests; fi
