---
Name: silverstripe-seeder
After: 'framework/*'
---

Seeder\Seeder:
  providers:
    - \Seeder\Providers\DataTypeProvider
    - \Seeder\Providers\DateProvider
    - \Seeder\Providers\FakerProvider
    - \Seeder\Providers\HTMLProvider
    - \Seeder\Providers\ImageProvider
    - \Seeder\Providers\MemberProvider
    - \Seeder\Providers\FirstObjectProvider
    - \Seeder\Providers\PageTitleProvider
    - \Seeder\Providers\RandomObjectProvider
    - \Seeder\Providers\SortProvider
    - \Seeder\Providers\UniqueProvider
    - \Seeder\Providers\URLSegmentProvider
    - \Seeder\Providers\ValueProvider
    - \Seeder\Providers\WhereProvider
    # tests
    - \Seeder\Tests\TestProvider
  empty_shorthand_provider: \Seeder\Providers\ValueProvider
  default_provider: \Seeder\Providers\DataTypeProvider
  default_providers:
    Image: \Seeder\Providers\ImageProvider
  default_ignores:
    SilverStripe\CMS\Model\SiteTree:
      - Sort
      - URLSegment
      - MenuTitle
      - HasBrokenFile
      - HasBrokenLink
      - ReportClass
      - Priority
      - Version
      - MetaTitle
      - MetaDescription
      - ExtraMeta
    SilverStripe\Security\Member:
      - TempIDHash
      - TempIDExpired
      - RememberLoginToken
      - NumVisit
      - LastVisited
      - AutoLoginHash
      - AutoLoginExpired
      - PasswordEncryption
      - Salt
      - PasswordExpiry
      - LockedOutUntil
      - Locale
      - FailedLoginCount
      - DateFormat
      - TimeFormat
  default_values:
    SilverStripe\CMS\Model\SiteTree:
      ShowInMenus: 0
      ShowInSearch: 1
      CanViewType: Anyone
      CanEditType: LoggedInUsers


SilverStripe\Control\Director:
  rules:
    'seed' : '\Seeder\Tasks\Seed'
    'unseed' : '\Seeder\Tasks\Unseed'
